request_area_preset:
  description: "Requests Dynalite to report the preset for an area."
  fields:
    host:
      description: "Host gateway IP to send to or all configured gateways if not specified."
      example: "192.168.0.101"
    area:
      description: "Area to request the preset reported"
      example: 2
    channel:
      description: "Channel to request the preset to be reported from. Default is channel 1"
      example: 1

